language: node_js
node_js:
  - "7"
sudo: false
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script:
  - yarn run lint
  - yarn test
after_script: yarn add coveralls && cat ./coverage/lcov.info | coveralls
